### ISSUE TITLE
Some Bugs/Improvements

### ISSUE THREAD

**Issue by darkyy1994** [stormmane/bugtracker#1]
1.) Does the Events really work? I cant seem to find anything i tryed to find them but i couldnt 
http://prntscr.com/mskz0o
http://prntscr.com/mslf8n

2.) PLEASE higher the amount of intances per hour http://prntscr.com/mslb02 http://prntscr.com/mslt4b

3.) .vip instance doesnt work (I am vip but i cant teleport there) I tryed to walk there and go inside, doesnt work too http://prntscr.com/msljod

4.) Onyxia´s Lair have 3x Onyxia its cool because more loot but im not sure if thats planed :P http://prntscr.com/mslmi7

5.) Transmog NPC doesnt work, it dont show any items (No standart wow items, no custom items) http://prntscr.com/msctwp

**Comment by 73CHFR34K** [comment]
Fixxed
